import {
  Activity,
  ArrowUpRight,
  BarChart3,
  Check,
  CircleHelp,
  Fingerprint,
  LockKeyhole,
  Plus,
  ShieldCheck,
  Vote,
} from "lucide-react";
import { BallotCard } from "./BallotCard";
import type { Ballot, Section } from "./types";

export function Overview({ ballots, onVote, onCreate, onSection }: { ballots: Ballot[]; onVote: (ballot: Ballot) => void; onCreate: () => void; onSection: (section: Section) => void }) {
  const featured = ballots[0];
  const recent = [{ label: "Proof verified", detail: "Ballot 041 · 2 min ago", icon: ShieldCheck, tone: "mint" }, { label: "New ballot created", detail: "Network upgrade 7B · 18 min ago", icon: Plus, tone: "violet" }, { label: "Tally checkpoint", detail: "Treasury Q4 · 1 hr ago", icon: BarChart3, tone: "blue" }];
  return <>
    <section className="hero-row"><div><p className="eyebrow"><span className="eyebrow-mark" /> Midnight network · private governance</p><h1>Decisions that stay<br /><em>yours.</em></h1><p className="hero-copy">Vote with confidence. VotePriv makes every ballot <strong>private for the voter</strong> and <strong>verifiable for everyone.</strong></p><div className="hero-actions"><button className="primary-button" onClick={() => onVote(featured)}><Vote size={16} /> Vote on featured ballot</button><button className="secondary-button" onClick={onCreate}><Plus size={16} /> Create ballot</button></div></div><div className="hero-proof-card"><div className="proof-card-grid" /><div className="proof-card-top"><span className="mini-label">LIVE PROOF LAYER</span><span className="network-dot"><span /> Testnet</span></div><div className="proof-visual"><div className="proof-core"><Fingerprint size={30} /><span className="core-dot" /></div><div className="proof-label label-one"><span /> Private input</div><div className="proof-label label-two"><span /> Public proof</div><div className="proof-line line-one" /><div className="proof-line line-two" /></div><div className="proof-card-bottom"><div><strong>zk-verified</strong><span>without revealing the vote</span></div><ArrowUpRight size={17} /></div></div></section>
    <section className="metric-grid"><div className="metric-card"><div className="metric-icon mint"><Activity size={18} /></div><span>Active ballots</span><strong>12</strong><small>Demo data</small></div><div className="metric-card"><div className="metric-icon violet"><ShieldCheck size={18} /></div><span>Verified votes</span><strong>4,286</strong><small>Demo data</small></div><div className="metric-card"><div className="metric-icon blue"><LockKeyhole size={18} /></div><span>Tally during voting</span><strong>Sealed</strong><small>Enforced by the contract</small></div><div className="metric-card network-card"><div className="metric-network-line"><span className="pulse-dot" /> Midnight testnet <span className="network-live">Operational</span></div><div className="network-bar"><span /><span /><span /><span /><span /><span /><span /><span /></div><small>Last block <strong>1,928,441</strong> · Demo data</small></div></section>
    <section className="content-grid"><div className="main-column"><div className="section-heading"><div><p className="eyebrow">Make your voice count</p><h2>Featured ballot</h2></div><button className="link-button" onClick={() => onSection("Live ballots")}>View all ballots <ArrowUpRight size={14} /></button></div><BallotCard ballot={featured} onVote={onVote} /><div className="section-heading lower-heading"><div><p className="eyebrow">Browse the room</p><h2>Active ballots</h2></div><button className="link-button" onClick={() => onSection("Live ballots")}>Explore <ArrowUpRight size={14} /></button></div><div className="mini-ballot-list">{ballots.slice(1, 3).map((ballot) => <BallotCard key={ballot.id} ballot={ballot} onVote={onVote} />)}</div></div><aside className="side-column"><div className="side-panel"><div className="panel-heading"><div><p className="eyebrow">A quiet audit trail</p><h2>Recent activity</h2></div><button className="icon-button" aria-label="View activity"><ArrowUpRight size={16} /></button></div><div className="activity-list">{recent.map(({ label, detail, icon: Icon, tone }) => <div className="activity-item" key={label}><div className={`activity-icon ${tone}`}><Icon size={16} /></div><div><strong>{label}</strong><span>{detail}</span></div><span className="activity-check"><Check size={12} /></span></div>)}</div><button className="panel-link" onClick={() => onSection("Results")}>Open audit log <ArrowUpRight size={14} /></button></div><div className="side-panel how-panel"><div className="panel-heading"><div><p className="eyebrow mint-text">Built for trust</p><h2>How it works</h2></div><CircleHelp size={18} /></div><div className="how-step"><span>01</span><div><strong>Prove eligibility</strong><p>Show you can vote without revealing who you are.</p></div></div><div className="how-step"><span>02</span><div><strong>Seal your choice</strong><p>Your vote becomes a private commitment.</p></div></div><div className="how-step"><span>03</span><div><strong>Verify the result</strong><p>Anyone can audit the aggregate tally.</p></div></div><button className="panel-link" onClick={() => onSection("Docs")}>Read the privacy model <ArrowUpRight size={14} /></button></div></aside></section>
  </>;
}
